# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV["LC_ALL"] = "en_US.UTF-8"

## Documentation for VirtualBox-specific features:
# https://www.vagrantup.com/docs/providers/virtualbox/networking
# VirtualBox networking: https://www.virtualbox.org/manual/ch06.html
# modifyvm command: https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm

Vagrant.configure("2") do |config|
  ## Disable auto update of VirtualBox Guest Additions
  config.vbguest.auto_update = false

  ## Lab 1
  config.vm.define "lab1" do |subconfig|
    # Set box and hostname
    subconfig.vm.box = "ubuntu/jammy64"    
    subconfig.vm.hostname = "lab1"
    # Set up networks
    subconfig.vm.network "private_network",
      ip: "fd01:2345:6789:abc1::1",
      netmask: "64",
      virtualbox__intnet: "intnet1"
    subconfig.vm.network "private_network",
      ip: "192.168.1.1",
      netmask: "16",
      virtualbox__intnet: "intnet2"
    subconfig.vm.provider "virtualbox" do |vb|
      # Custom VM Group, memory, and CPU cores
      vb.customize ["modifyvm", :id, "--groups", "/lab"]
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "14"]
    end
    # Add provisioning scripts
    subconfig.vm.provision "shell", inline: <<-SHELL
      sudo echo "fd01:2345:6789:abc1::2 lab2" | sudo tee -a /etc/hosts
      sudo echo "192.168.2.1 lab3" | sudo tee -a /etc/hosts
      sudo echo "fd01:2345:6789:abc2::2 lab4" | sudo tee -a /etc/hosts
      sudo sysctl -w net.ipv4.ip_forward=1
      sudo sysctl -w net.ipv6.conf.default.forwarding=1
      sudo sysctl -w net.ipv6.conf.all.forwarding=1
      sudo sysctl -w net.ipv6.conf.enp0s3.accept_ra=0
      sudo sed -i 's/archive.ubuntu./fi.archive.ubuntu./g' /etc/apt/sources.list
      sudo apt update
      sudo apt install -y net-tools traceroute nmap lynx
    SHELL
    subconfig.vm.provision :shell, privileged: false, path: "scripts/lab1.sh"
  end

  ## Lab 2
  config.vm.define "lab2" do |subconfig|
    # Set box and hostname
    subconfig.vm.box = "ubuntu/jammy64"
    subconfig.vm.hostname = "lab2"
    # Set up networks
    subconfig.vm.network "private_network",
      ip: "fd01:2345:6789:abc1::2",
      netmask: "64",
      virtualbox__intnet: "intnet1"
    subconfig.vm.provider "virtualbox" do |vb|
      # Custom VM Group, memory, and CPU cores
      vb.customize ["modifyvm", :id, "--groups", "/lab"]
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "14"]
    end
    # Add provisioning scripts
    subconfig.vm.provision "shell", inline: <<-SHELL
      sudo echo "fd01:2345:6789:abc1::1 lab1" | sudo tee -a /etc/hosts
      sudo echo "fd01:2345:6789:abc2::1 lab3" | sudo tee -a /etc/hosts
      sudo echo "fd01:2345:6789:abc2::2 lab4" | sudo tee -a /etc/hosts
      sudo sysctl -w net.ipv4.ip_forward=1
      sudo sysctl -w net.ipv6.conf.default.forwarding=1
      sudo sysctl -w net.ipv6.conf.all.forwarding=1
      sudo sysctl -w net.ipv6.conf.enp0s3.accept_ra=0
      sudo sed -i 's/archive.ubuntu./fi.archive.ubuntu./g' /etc/apt/sources.list
      sudo apt update
      sudo apt install -y net-tools
    SHELL
    subconfig.vm.provision :shell, privileged: false, path: "scripts/lab2.sh"
  end

  ## Lab 3
  config.vm.define "lab3" do |subconfig|
    # Set box and hostname
    subconfig.vm.box = "ubuntu/jammy64"
    subconfig.vm.hostname = "lab3"
    # Set up networks
    subconfig.vm.network "public_network",
      bridge: [ "wlp0s20f3", "enp43s0" ]
    subconfig.vm.network "private_network",
      ip: "192.168.2.1",
      netmask: "16",
      virtualbox__intnet: "intnet2"
    subconfig.vm.network "private_network",
      ip: "fd01:2345:6789:abc2::1",
      netmask: "64",
      virtualbox__intnet: "intnet3"
    subconfig.vm.provider "virtualbox" do |vb|
      # Custom VM Group, memory, and CPU cores
      vb.customize ["modifyvm", :id, "--groups", "/lab"]
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "14"]
    end
    # Add provisioning scripts
    subconfig.vm.provision "shell", inline: <<-SHELL
      sudo echo "192.168.1.1 lab1" | sudo tee -a /etc/hosts
      sudo echo "fd01:2345:6789:abc1::1 lab1" | sudo tee -a /etc/hosts
      sudo echo "fd01:2345:6789:abc1::2 lab2" | sudo tee -a /etc/hosts
      sudo echo "fd01:2345:6789:abc2::2 lab4" | sudo tee -a /etc/hosts
      sudo sysctl -w net.ipv4.ip_forward=1
      sudo sysctl -w net.ipv6.conf.default.forwarding=1
      sudo sysctl -w net.ipv6.conf.all.forwarding=1
      sudo sysctl -w net.ipv6.conf.enp0s3.accept_ra=0
      sudo sed -i 's/archive.ubuntu./fi.archive.ubuntu./g' /etc/apt/sources.list
      sudo apt update
      sudo apt install -y net-tools
    SHELL
    subconfig.vm.provision :shell, privileged: false, path: "scripts/lab3.sh"
  end

  config.vm.define "lab4" do |subconfig|
    # Set box and hostname
    subconfig.vm.box = "ubuntu/jammy64"
    subconfig.vm.hostname = "lab4"
    # Set up networks
    subconfig.vm.network "private_network",
      ip: "fd01:2345:6789:abc2::2",
      netmask: "64",
      virtualbox__intnet: "intnet3"
    subconfig.vm.provider "virtualbox" do |vb|
      # Custom VM Group, memory, and CPU cores
      vb.customize ["modifyvm", :id, "--groups", "/lab"]
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "14"]
    end
    # Add provisioning scripts
    subconfig.vm.provision "shell", inline: <<-SHELL
      sudo echo "fd01:2345:6789:abc1::1 lab1" | sudo tee -a /etc/hosts
      sudo echo "fd01:2345:6789:abc1::2 lab2" | sudo tee -a /etc/hosts
      sudo echo "fd01:2345:6789:abc2::1 lab3" | sudo tee -a /etc/hosts
      sudo sysctl -w net.ipv4.ip_forward=1
      sudo sysctl -w net.ipv6.conf.default.forwarding=1
      sudo sysctl -w net.ipv6.conf.all.forwarding=1
      sudo sysctl -w net.ipv6.conf.enp0s3.accept_ra=0
      sudo sed -i 's/archive.ubuntu./fi.archive.ubuntu./g' /etc/apt/sources.list
      sudo apt update
      sudo apt install -y net-tools
    SHELL
    subconfig.vm.provision :shell, privileged: false, path: "scripts/lab4.sh"
  end
end
