apiVersion: v1
kind: Pod
metadata:
  name: sa-frontend2
  labels:
    app: sa-frontend
spec:
  containers:
    - image: hollowman6/sa-frontend:minikube
      name: sa-frontend
      ports:
        - containerPort: 80